package main

func main() {
	arrays()
	slices()
	maps()
	rangeFunc()
	funcs()
	printVariadic()
	closure()
	recursion()
	pointers()
	stringsandrunes()
	structFunc()
	methods()
	callInterfaceMethods()
	structEmbedding()
	buildList() //generics
	throwError()
	goRoutines()
	channelConcepts()
	channelBuffering()
	channelSynchronization()
	channelDirection()
	selectStatement()
	timeouts()
	nonBlockingChannelOperations()
	closingChannels()
	timers()
	tickers()
}
